from Bio.Seq import Seq

original_sequence = Seq("gcggccgctgctttctaaatctatgcgtactatgttggatactcaattcggccttgcgtgatgggacacccagccactgcttcttggtccgatgtccacaagtctagagaacttaaatgagatcaaaggacgtcaggacccaagagtttccaatatcgcggcgacagatagaataccacaaagttcccctgatcatcgtgacccatactacacccagaataggctcgcatataatttttgcatacttacgggggcccgatgcactaatgcttgatgagagttttacaaccaatctaatagccgggagcattgtaagaattcacctcgaggtagcgtattgactcgcctacagacgagcgtgctccgacgcaaagtttaaaaaagtgaggatgtcttagttcgtaattttcccggtataaatatatgaccaacattgtctttgacagtgtgatcgtccccataaacacaccgggggatcagcgcgttcttctattgctttagccgaaatcgatgcctccgagtagtcgaagcccaccacaccacctgatcggtacagcagggtgcacgcttggtcgagggccccgccatgccccgccgggaccctttgcaacggcctacgatgcgcggccaagcacttctgcaatctaaatttctgcggtcggatgtgacggcaccgtttgtgaaagtgtaactcctatggagccgccaggccgggcatttatcgaattatagttgctcgtgggagggtctcagtcgacagctctaaaacttaaagccgagtacctagcatgcataaggctataagtcaacgtgcgcacctaccacgacctcggatactaccggggcgaaatagttcattcatctgtttttatacaacgcctctgccaagcgtctccctgacagccctacccacgccctgtataattggagcgttgtttactgtttcgccccgtgtcttctgggcgtcccacagtaacgggaatcactgcctaatgcttgg")
print(original_sequence)

reverse_complement_sequence = original_sequence.reverse_complement()
print(reverse_complement_sequence)