from Bio.Seq import Seq

dna_sequence = Seq("gcggccgctgctttctaaatctatgcgtactaaatgttggatactcaattcggccttgcgtgatgggacacccagccactgcttcttggtccgatgtccacaagtctagagaacttaaatgagatcaaaggacgtcaggacccaagagtttccaatatcgcggcgacagatagaataccacaaagttcccctgatcatcgtgacccatactacacccagaataggctcgcatataatttttgcatacttacgggggcccgatgcactaatgcttgatgagagttttacaaccaatctaatagccgggagcattgtaagaattcacctcgaggtagcgtattgactcgcctacagacgagcgtgctccgacgcaaagtttaaaaaagtgaggatgtcttagttcgtaattttcccggtataaatatatgaccaacattgtctttgacagtgtgatcgtccccataaacacaccgggggatcagcgcgttcttctattgctttagccgaaatcgatgcctccgagtagtcgaagcccaccacaccacctgatcggtacagcagggtgcacgcttggtcgagggccccgccatgccccgccgggaccctttgcaacggcctacgatgcgcggccaagcacttctgcaatctaaatttctgcggtcggatgtgacggcaccgtttgtgaaagtgtaactcctatggagccgccaggccgggcatttatcgaattatagttgctcgtgggagggtctcagtcgacagctctaaaacttaaagccgagtacctagcatgcataaggctataagtcaacgtgcgcacctaccacgacctcggatactaccggggcgaaatagttcattcatctgtttttatacaacgcctctgccaagcgtctccctgacagccctacccacgccctgtataattggagcgttgtttactgtttcgccccgtgtcttctgggcgtcccacagtaacgggaatcactgcctaatgcttgg")


print(dna_sequence.startswith("gcg"))
print(dna_sequence.startswith("gcc"))
print(dna_sequence.startswith("ggg"))
print()

print(dna_sequence.upper())
print()

